version: "3.8"
services:
  xv6:
    build: .
    container_name: xv6
    volumes:
      - .:/xv6
    working_dir: /xv6

  xv6-gdb:
    build: .
    container_name: xv6-gdb
    volumes:
      - .:/xv6
    working_dir: /xv6
    command: make qemu-gdb
